export const twitter = "https://www.twitter.com"
export const instagram = "https://www.instagram.com"
export const facebook = "https://www.facebook.com"
export const mail = "mailto:elpis409@gmail.com"
// export const tel = "tel:+97455925933"
